variable "kubeconfig_path" {
  description = "Path to the kubeconfig generated by terraform/infra."
  type        = string
  default     = "../../_out/kubeconfig"
}

variable "cluster_vip" {
  description = "Kubernetes API VIP."
  type        = string
  default     = "192.168.80.10"
}

variable "gateway_load_balancer_ip" {
  description = "MetalLB IP requested by the shared Cilium Gateway."
  type        = string
  default     = "192.168.80.30"
}

variable "pihole_primary_ip" {
  description = "External primary Pi-hole address. This must not be in the MetalLB pool."
  type        = string
  default     = "192.168.80.31"
}

variable "pihole_secondary_ip" {
  description = "Kubernetes secondary Pi-hole LoadBalancer address."
  type        = string
  default     = "192.168.80.32"
}

variable "forgejo_ssh_ip" {
  description = "Dedicated Forgejo SSH LoadBalancer address."
  type        = string
  default     = "192.168.80.33"
}

variable "bootstrap_repo_url" {
  description = "Public off-cluster bootstrap and disaster-recovery repository."
  type        = string
  default     = "https://github.com/j4v3l/proxmox-talos-lab.git"
}

variable "bootstrap_revision" {
  description = "Protected bootstrap repository revision."
  type        = string
  default     = "main"
}

variable "apps_repo_url" {
  description = "Authoritative private Forgejo application repository."
  type        = string
  default     = "https://git.lab.home.arpa/j4v3l/talos-apps.git"
}

variable "apps_revision" {
  description = "Protected application repository revision."
  type        = string
  default     = "main"
}

variable "lab_base_domain" {
  description = "LAN/VPN-only DNS suffix."
  type        = string
  default     = "lab.home.arpa"
}

variable "gateway_api_version" {
  description = "Gateway API CRD release."
  type        = string
  default     = "v1.4.1"
}

variable "gateway_api_manifest_sha256" {
  description = "Expected SHA-256 of the pinned Gateway API standard-install manifest."
  type        = string
  default     = "73b91b77f6be023a8c92c969fc664e5bd3b1a28aea59eac9ebc904607354dad2"
}

variable "cilium_chart_version" {
  description = "Cilium Helm chart version."
  type        = string
  default     = "1.19.6"
}

variable "argocd_chart_version" {
  description = "Argo CD Helm chart version."
  type        = string
  default     = "9.5.17"
}

variable "argocd_oidc_client_id" {
  description = "Non-secret Authentik OIDC client ID. The client secret is injected directly into argocd-secret outside Terraform."
  type        = string
  default     = "argocd"
}

variable "argocd_oidc_issuer" {
  description = "Authentik OIDC issuer URL."
  type        = string
  default     = "https://auth.lab.home.arpa/application/o/argocd/"
}
