variable "kubeconfig_path" {
  description = "Path to the kubeconfig generated by terraform/infra."
  type        = string
  default     = "../../_out/kubeconfig"
}

variable "cluster_vip" {
  description = "Kubernetes API VIP."
  type        = string
  default     = "192.168.80.10"
}

variable "ingress_load_balancer_ip" {
  description = "MetalLB IP assigned to ingress-nginx."
  type        = string
  default     = "192.168.80.30"
}

variable "metallb_address_pool" {
  description = "MetalLB L2 address pool."
  type        = list(string)
  default     = ["192.168.80.30-192.168.80.49"]
}

variable "gitops_repo_url" {
  description = "Optional GitHub repository URL containing this repository after you push it. Leave empty for local Terraform-managed smoke apps."
  type        = string
  default     = ""
}

variable "gitops_revision" {
  description = "Git revision Argo CD should sync."
  type        = string
  default     = "main"
}

variable "lab_base_domain" {
  description = "Base DNS suffix for local lab hostnames."
  type        = string
  default     = "lab.home.arpa"
}

variable "adguard_dns_ip" {
  description = "Dedicated MetalLB IP for the AdGuard Home DNS service."
  type        = string
  default     = "192.168.80.31"
}

variable "rancher_hostname" {
  description = "Rancher ingress hostname."
  type        = string
  default     = "rancher.192.168.80.30.sslip.io"
}

variable "argocd_hostname" {
  description = "Argo CD ingress hostname."
  type        = string
  default     = "argocd.192.168.80.30.sslip.io"
}

variable "rancher_bootstrap_password" {
  description = "Optional Rancher bootstrap password. If null, Terraform generates one and stores it in state."
  type        = string
  default     = null
  sensitive   = true
}

variable "cilium_chart_version" {
  description = "Cilium Helm chart version."
  type        = string
  default     = "1.19.4"
}

variable "cert_manager_chart_version" {
  description = "cert-manager Helm chart version."
  type        = string
  default     = "v1.20.2"
}

variable "metallb_chart_version" {
  description = "MetalLB Helm chart version."
  type        = string
  default     = "0.16.1"
}

variable "ingress_nginx_chart_version" {
  description = "ingress-nginx Helm chart version."
  type        = string
  default     = "4.15.1"
}

variable "argocd_chart_version" {
  description = "Argo CD Helm chart version."
  type        = string
  default     = "9.5.17"
}

variable "rancher_chart_version" {
  description = "Rancher Helm chart version."
  type        = string
  default     = "2.14.2"
}

variable "longhorn_chart_version" {
  description = "Longhorn Helm chart version used by local smoke bootstrap when gitops_repo_url is empty."
  type        = string
  default     = "1.11.2"
}

variable "metrics_server_chart_version" {
  description = "metrics-server Helm chart version."
  type        = string
  default     = "3.13.0"
}
