ingressClassName: nginx
aliases:
  - name: argocd
    namespace: argocd
    serviceName: argo-cd-argocd-server
    servicePort: 80
    host: argocd.lab.home.arpa
  - name: rancher
    namespace: cattle-system
    serviceName: rancher
    servicePort: 80
    host: rancher.lab.home.arpa
