---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: terraform
    directory: /terraform/infra
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/platform
    schedule:
      interval: weekly
