{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: {{ .name | quote }}
  url: {{ .url | quote }}
  type: {{ .type | quote }}
  enableOCI: {{ .enableOCI | quote }}
---
{{- end }}
