apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ required "gitOpsRepoUrl is required" .Values.gitOpsRepoUrl | quote }}
    targetRevision: {{ .Values.gitOpsRevision | quote }}
    path: gitops/clusters/talos-lab
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
