apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-bootstrap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bootstrap
  source:
    repoURL: {{ required "bootstrapRepoUrl is required" .Values.bootstrapRepoUrl | quote }}
    targetRevision: {{ .Values.bootstrapRevision | quote }}
    path: gitops/clusters/talos-lab
    helm:
      values: |
        bootstrapRepoUrl: {{ .Values.bootstrapRepoUrl | quote }}
        bootstrapRevision: {{ .Values.bootstrapRevision | quote }}
        appsRepoUrl: {{ .Values.appsRepoUrl | quote }}
        appsRevision: {{ .Values.appsRevision | quote }}
        labBaseDomain: {{ .Values.labBaseDomain | quote }}
        gatewayLoadBalancerIp: {{ .Values.gatewayLoadBalancerIp | quote }}
        piholePrimaryIp: {{ .Values.piholePrimaryIp | quote }}
        piholeSecondaryIp: {{ .Values.piholeSecondaryIp | quote }}
        forgejoSshIp: {{ .Values.forgejoSshIp | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
