apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ required "gitOpsRepoUrl is required" .Values.gitOpsRepoUrl | quote }}
    targetRevision: {{ .Values.gitOpsRevision | quote }}
    path: gitops/apps/forgejo-runner
    helm:
      values: |
        hostAliases:
          - ip: {{ .Values.ingressLoadBalancerIp | quote }}
            hostnames:
              - {{ include "talos-lab.labHost" (dict "root" . "name" "git") | quote }}
        extraEnv:
          - name: GIT_SSL_NO_VERIFY
            value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
