apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.55.0
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          useTestSchema: true
          limits_config:
            retention_period: 72h
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi
            storageClass: longhorn-lab-single
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 768Mi
        gateway:
          enabled: false
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        minio:
          enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
