apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: {{ .Values.appsRepoUrl | quote }}
    targetRevision: {{ .Values.appsRevision | quote }}
    path: platform/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
