apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-home-bootstrap
data:
  AdGuardHome.yaml: |
    http:
      address: 0.0.0.0:3000
      session_ttl: 720h
    users: []
    language: en
    theme: auto
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
      protection_enabled: true
      filtering_enabled: true
      upstream_mode: parallel
      bootstrap_dns:{{ .Values.bootstrapDns | toYaml | nindent 8 }}
      upstream_dns:{{ .Values.upstreamDns | toYaml | nindent 8 }}
    schema_version: 29
