apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-home
spec:
  ingressClassName: nginx
  rules:
{{- range .Values.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-home-ui
                port:
                  name: web
{{- end }}
